version: 2

updates:
# --- Frontend npm ecosystem ---
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "axios"
    commit-message:
      prefix: "Version Update"
      include-cope: true
