version: 2

updates:
# --- Frontend npm ecosystem ---
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "axios"
        versions: [ ">=1.12.0" ]
